site_name: diff-em
site_url: https://elkins.github.io/diff-em/
site_description: Differentiable Cryo-EM map fitting in JAX
site_author: George Elkins

theme:
  name: material
  palette:
    scheme: slate
    primary: light-blue
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - Theory: theory.md
  - API Reference: api/kernels.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
